import type { Rule } from 'sanity';

export default {
  name: 'userResponseV2',
  type: 'document',
  title: 'User Response V2',
  fields: [
    {
      name: 'section',
      type: 'string',
      title: 'Department / Section',
      options: {
        layout: 'dropdown',
        list: [
          // --- STUDENT ---
          { title: '3D Arts', value: '3d-arts' },
          { title: 'Animation', value: 'animation' },
          { title: 'Architecture', value: 'architecture' },
          { title: 'Art Education', value: 'art-education' },
          { title: 'Ceramics', value: 'ceramics' },
          { title: 'Communication Design', value: 'communication-design' },
          { title: 'Creative Writing', value: 'creative-writing' },
          { title: 'Design Innovation', value: 'design-innovation' },
          { title: 'Digital Media', value: 'digital-media' },
          { title: 'Dynamic Media Institute', value: 'dynamic-media-institute' },
          { title: 'Fashion Design', value: 'fashion-design' },
          { title: 'Fibers', value: 'fibers' },
          { title: 'Film/Video', value: 'film-video' },
          { title: 'Fine Arts 2D', value: 'fine-arts-2d' },
          { title: 'Furniture Design', value: 'furniture-design' },
          { title: 'Glass', value: 'glass' },
          { title: 'History of Art', value: 'history-of-art' },
          { title: 'Humanities', value: 'humanities' },
          { title: 'Illustration', value: 'illustration' },
          { title: 'Industrial Design', value: 'industrial-design' },
          { title: 'Integrative Sciences & Biological Arts', value: 'integrative-sciences' },
          { title: 'Jewelry & Metalsmithing', value: 'jewelry-metalsmithing' },
          { title: 'Liberal Arts', value: 'liberal-arts' },
          { title: 'MFA Low Residency', value: 'mfa-low-residency' },
          { title: 'MFA Low Residency | Studio Foundation', value: 'mfa-low-residency-foundation' },
          { title: 'MFA Studio Arts | Fine Arts 2D', value: 'mfa-studio-arts' },
          { title: 'Painting', value: 'painting' },
          { title: 'Photography', value: 'photography' },
          { title: 'Printmaking', value: 'printmaking' },
          { title: 'Sculpture', value: 'sculpture' },
          { title: 'Studio Arts', value: 'studio-arts' },
          { title: 'Studio for Interrelated Media', value: 'studio-interrelated-media' },
          { title: 'Studio Foundation', value: 'studio-foundation' },
          { title: 'Visual Storytelling & Comic Arts', value: 'visual-storytelling' },

          // --- STAFF ---
          { title: 'Academic Affairs', value: 'academic-affairs' },
          { title: 'Academic Resource Center', value: 'academic-resource-center' },
          { title: 'Administration & Finance', value: 'administration-finance' },
          { title: 'Administrative Services', value: 'administrative-services' },
          { title: 'Admissions', value: 'admissions' },
          { title: 'Artward Bound', value: 'artward-bound' },
          { title: 'Bookstore', value: 'bookstore' },
          { title: 'Bursar’s Office', value: 'bursar' },
          { title: 'Career Development', value: 'career-development' },
          { title: 'Center for Art & Community Partnerships', value: 'center-art-community' },
          { title: 'Community Health & Well-being', value: 'community-health' },
          { title: 'Compass', value: 'compass' },
          { title: 'Conference & Event Services', value: 'conference-event-services' },
          { title: 'Counseling Center', value: 'counseling-center' },
          { title: 'Facilities', value: 'facilities' },
          { title: 'Fiscal Affairs / Accounting Services', value: 'fiscal-accounting' },
          { title: 'Fiscal Affairs / Budget Office', value: 'fiscal-budget' },
          { title: 'Graduate Programs', value: 'graduate-programs' },
          { title: 'Health Office', value: 'health-office' },
          { title: 'Housing & Residence Life', value: 'housing-residence-life' },
          { title: 'Human Resources', value: 'human-resources' },
          { title: 'Institutional Advancement', value: 'institutional-advancement' },
          { title: 'Institutional Research & Strategic Effectiveness', value: 'institutional-research' },
          { title: 'International Education Center', value: 'international-education' },
          { title: 'Justice, Equity, & Transformation', value: 'justice-equity' },
          { title: 'Library', value: 'library' },
          { title: 'Marketing & Communications', value: 'marketing-communications' },
          { title: 'MassArt Art Museum', value: 'maam' },
          { title: 'MassArt Foundation', value: 'foundation' },
          { title: 'President’s Office', value: 'president-office' },
          { title: 'Professional & Continuing Education', value: 'pce' },
          { title: 'Public Safety', value: 'public-safety' },
          { title: 'Registrar’s Office', value: 'registrar' },
          { title: 'Student Development', value: 'student-development' },
          { title: 'Student Engagement', value: 'student-engagement' },
          { title: 'Student Financial Assistance', value: 'student-financial-assistance' },
          { title: 'Sustainability', value: 'sustainability' },
          { title: 'Technology', value: 'technology' },
          { title: 'Woodshop', value: 'woodshop' },
          { title: 'Youth Programs', value: 'youth-programs' },

          // ---- Visitor bucket ----
          { title: 'Visitor', value: 'visitor' },
        ],
      },
      validation: (rule: Rule) => rule.required(),
    },

    // answers
    { name: 'question1', type: 'string', title: 'Answer to Question 1' },
    { name: 'question2', type: 'string', title: 'Answer to Question 2' },
    { name: 'question3', type: 'string', title: 'Answer to Question 3' },
    { name: 'question4', type: 'string', title: 'Answer to Question 4' },
    { name: 'question5', type: 'string', title: 'Answer to Question 5' },

    { name: 'submittedAt', type: 'datetime', title: 'Submitted At' },
  ],
};
